id = "move"
name = "Move"
version = "0.0.4"
schema_version = 1
authors = [
    "Alexandros Tzimas <alex.tzimas@mystenlabs.com>",
    "lispking <lispking@qq.com>",
]
description = "Move language support for the zed editor."
repository = "https://github.com/MystenLabs/move-zed-extension"
snippets = "./snippets/move.json"

[language_servers.move-language-server]
name = "move"
language = "Move"

[grammars.move]
repository = "https://github.com/tzakian/tree-sitter-move"
commit = "f5b37f63569f69dfbe7a9950527786d2f6b1d35c"
